repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--line-length", "120"]

  - repo: https://github.com/pycqa/pylint
    rev: v2.13.8
    hooks:
      - id: pylint
        args:
          - --rcfile=tox.ini
          - --disable=E0401
          - --fail-under=8

#  - repo: https://gitlab.com/pycqa/flake8
#    rev: 3.9.2
#    hooks:
#      - id: flake8

#  - repo: https://github.com/pycqa/bandit
#    rev: 1.7.4
#    hooks:
#      - id: bandit
#        args: [-c, bandit.yaml]
